add SpanQuery-related tests to TestSolrCoreParser
bloomberg/lucene-solr pull request #209
Opened 2017-01-10 13:25 UTC by cpoerschke

2017-01-12 20:48 UTC, dcollins53 submitted a review, later dismissed
I think it holds together, but we can discuss tomorrow

2017-01-12 20:48 UTC, dcollins53 commented on solr/core/src/java/org/apache/solr/search/SolrCoreParser.java
> +  @Override
Not an override if the parent doesn't support it.

2017-01-12 20:48 UTC, dcollins53 commented on solr/core/src/java/org/apache/solr/search/SolrCoreParser.java
> +public class SolrCoreParser extends CoreParser implements NamedListInitializedPlugin, SpanQueryBuilder {
This feels wrong.  I probably get why you are doing it (to prevent changes to core lucene), but it still feels like the wrong level for this.

2017-01-16 16:56 UTC, cpoerschke commented on solr/core/src/java/org/apache/solr/search/SolrCoreParser.java
> +            new Object[] {defaultField, analyzer, req, this, this});
An alternative constructor signature might be `..., req, this` instead of `..., req, this, this` here.

2017-01-16 17:58 UTC, dcollins53 commented on solr/core/src/java/org/apache/solr/search/SolrCoreParser.java
> +            new Object[] {defaultField, analyzer, req, this, this});
@cpoerschke yes, I think that would work better as an API for the individual builders.

2017-01-16 18:01 UTC, dcollins53 commented on solr/core/src/java/org/apache/solr/search/SolrCoreParser.java
> +            new Object[] {defaultField, analyzer, req, this, this});
Do I need to add a comment to make this non-mergable...

2017-01-16 18:02 UTC, dcollins53 requested changes
As per discussion we should simplify the builder API

2017-01-17 15:58 UTC, dcollins53 approved these changes
One unused import I think but seems okay in general

2017-01-17 15:58 UTC, dcollins53 commented on solr/core/src/java/org/apache/solr/search/SolrSpanQueryBuilder.java
> +import org.apache.lucene.queryparser.xml.QueryBuilder;
Is this used?

2017-01-23 17:35 UTC, merged